/**
 * generated by Xtext 2.12.0
 */
package it.unige.dibris.trace_expression_language.tExp;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atom Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.AtomExpression#getAtom <em>Atom</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.AtomExpression#getTerms <em>Terms</em>}</li>
 * </ul>
 *
 * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getAtomExpression()
 * @model
 * @generated
 */
public interface AtomExpression extends PrologExpression
{
  /**
   * Returns the value of the '<em><b>Atom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Atom</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Atom</em>' attribute.
   * @see #setAtom(String)
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getAtomExpression_Atom()
   * @model
   * @generated
   */
  String getAtom();

  /**
   * Sets the value of the '{@link it.unige.dibris.trace_expression_language.tExp.AtomExpression#getAtom <em>Atom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Atom</em>' attribute.
   * @see #getAtom()
   * @generated
   */
  void setAtom(String value);

  /**
   * Returns the value of the '<em><b>Terms</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Terms</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Terms</em>' containment reference.
   * @see #setTerms(PrologExpression)
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getAtomExpression_Terms()
   * @model containment="true"
   * @generated
   */
  PrologExpression getTerms();

  /**
   * Sets the value of the '{@link it.unige.dibris.trace_expression_language.tExp.AtomExpression#getTerms <em>Terms</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Terms</em>' containment reference.
   * @see #getTerms()
   * @generated
   */
  void setTerms(PrologExpression value);

} // AtomExpression
