/**
 * generated by Xtext 2.12.0
 */
package it.unige.dibris.trace_expression_language.tExp;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.Constraint#getLeft <em>Left</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.Constraint#getTogether <em>Together</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.Constraint#getRight <em>Right</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.Constraint#getSplit <em>Split</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.Constraint#getParMin <em>Par Min</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.Constraint#getParMax <em>Par Max</em>}</li>
 * </ul>
 *
 * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getConstraint()
 * @model
 * @generated
 */
public interface Constraint extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' reference list.
   * The list contents are of type {@link it.unige.dibris.trace_expression_language.tExp.Role}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' reference list.
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getConstraint_Left()
   * @model
   * @generated
   */
  EList<Role> getLeft();

  /**
   * Returns the value of the '<em><b>Together</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Together</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Together</em>' attribute.
   * @see #setTogether(String)
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getConstraint_Together()
   * @model
   * @generated
   */
  String getTogether();

  /**
   * Sets the value of the '{@link it.unige.dibris.trace_expression_language.tExp.Constraint#getTogether <em>Together</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Together</em>' attribute.
   * @see #getTogether()
   * @generated
   */
  void setTogether(String value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' reference list.
   * The list contents are of type {@link it.unige.dibris.trace_expression_language.tExp.Role}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' reference list.
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getConstraint_Right()
   * @model
   * @generated
   */
  EList<Role> getRight();

  /**
   * Returns the value of the '<em><b>Split</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Split</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Split</em>' attribute.
   * @see #setSplit(String)
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getConstraint_Split()
   * @model
   * @generated
   */
  String getSplit();

  /**
   * Sets the value of the '{@link it.unige.dibris.trace_expression_language.tExp.Constraint#getSplit <em>Split</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Split</em>' attribute.
   * @see #getSplit()
   * @generated
   */
  void setSplit(String value);

  /**
   * Returns the value of the '<em><b>Par Min</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Par Min</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Par Min</em>' attribute.
   * @see #setParMin(String)
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getConstraint_ParMin()
   * @model
   * @generated
   */
  String getParMin();

  /**
   * Sets the value of the '{@link it.unige.dibris.trace_expression_language.tExp.Constraint#getParMin <em>Par Min</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Par Min</em>' attribute.
   * @see #getParMin()
   * @generated
   */
  void setParMin(String value);

  /**
   * Returns the value of the '<em><b>Par Max</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Par Max</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Par Max</em>' attribute.
   * @see #setParMax(String)
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getConstraint_ParMax()
   * @model
   * @generated
   */
  String getParMax();

  /**
   * Sets the value of the '{@link it.unige.dibris.trace_expression_language.tExp.Constraint#getParMax <em>Par Max</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Par Max</em>' attribute.
   * @see #getParMax()
   * @generated
   */
  void setParMax(String value);

} // Constraint
