/**
 * generated by Xtext 2.12.0
 */
package it.unige.dibris.trace_expression_language.tExp;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Interaction Trace Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.InteractionTraceExpression#getRolesL <em>Roles L</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.InteractionTraceExpression#getRoles <em>Roles</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.InteractionTraceExpression#getTypes <em>Types</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.InteractionTraceExpression#getDecentralizedL <em>Decentralized L</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.InteractionTraceExpression#getDecentralized <em>Decentralized</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.InteractionTraceExpression#getPartitionL <em>Partition L</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.InteractionTraceExpression#getPartition <em>Partition</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.InteractionTraceExpression#getConstraintsL <em>Constraints L</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.InteractionTraceExpression#getConstraints <em>Constraints</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.InteractionTraceExpression#getGuiL <em>Gui L</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.InteractionTraceExpression#getGui <em>Gui</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.InteractionTraceExpression#getTargetL <em>Target L</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.InteractionTraceExpression#getTarget <em>Target</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.InteractionTraceExpression#getMinimalL <em>Minimal L</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.InteractionTraceExpression#getMinimal <em>Minimal</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.InteractionTraceExpression#getThresholdL <em>Threshold L</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.InteractionTraceExpression#getThreshold <em>Threshold</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.InteractionTraceExpression#getChannelsL <em>Channels L</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.InteractionTraceExpression#getChannels <em>Channels</em>}</li>
 * </ul>
 *
 * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getInteractionTraceExpression()
 * @model
 * @generated
 */
public interface InteractionTraceExpression extends TraceExpression
{
  /**
   * Returns the value of the '<em><b>Roles L</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Roles L</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Roles L</em>' attribute list.
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getInteractionTraceExpression_RolesL()
   * @model unique="false"
   * @generated
   */
  EList<String> getRolesL();

  /**
   * Returns the value of the '<em><b>Roles</b></em>' containment reference list.
   * The list contents are of type {@link it.unige.dibris.trace_expression_language.tExp.Role}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Roles</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Roles</em>' containment reference list.
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getInteractionTraceExpression_Roles()
   * @model containment="true"
   * @generated
   */
  EList<Role> getRoles();

  /**
   * Returns the value of the '<em><b>Types</b></em>' containment reference list.
   * The list contents are of type {@link it.unige.dibris.trace_expression_language.tExp.MsgEventType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Types</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Types</em>' containment reference list.
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getInteractionTraceExpression_Types()
   * @model containment="true"
   * @generated
   */
  EList<MsgEventType> getTypes();

  /**
   * Returns the value of the '<em><b>Decentralized L</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Decentralized L</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decentralized L</em>' attribute list.
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getInteractionTraceExpression_DecentralizedL()
   * @model unique="false"
   * @generated
   */
  EList<String> getDecentralizedL();

  /**
   * Returns the value of the '<em><b>Decentralized</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Decentralized</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decentralized</em>' attribute list.
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getInteractionTraceExpression_Decentralized()
   * @model unique="false"
   * @generated
   */
  EList<String> getDecentralized();

  /**
   * Returns the value of the '<em><b>Partition L</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Partition L</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Partition L</em>' attribute list.
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getInteractionTraceExpression_PartitionL()
   * @model unique="false"
   * @generated
   */
  EList<String> getPartitionL();

  /**
   * Returns the value of the '<em><b>Partition</b></em>' containment reference list.
   * The list contents are of type {@link it.unige.dibris.trace_expression_language.tExp.Partition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Partition</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Partition</em>' containment reference list.
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getInteractionTraceExpression_Partition()
   * @model containment="true"
   * @generated
   */
  EList<Partition> getPartition();

  /**
   * Returns the value of the '<em><b>Constraints L</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constraints L</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraints L</em>' attribute list.
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getInteractionTraceExpression_ConstraintsL()
   * @model unique="false"
   * @generated
   */
  EList<String> getConstraintsL();

  /**
   * Returns the value of the '<em><b>Constraints</b></em>' containment reference list.
   * The list contents are of type {@link it.unige.dibris.trace_expression_language.tExp.Constraint}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constraints</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraints</em>' containment reference list.
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getInteractionTraceExpression_Constraints()
   * @model containment="true"
   * @generated
   */
  EList<Constraint> getConstraints();

  /**
   * Returns the value of the '<em><b>Gui L</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Gui L</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gui L</em>' attribute list.
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getInteractionTraceExpression_GuiL()
   * @model unique="false"
   * @generated
   */
  EList<String> getGuiL();

  /**
   * Returns the value of the '<em><b>Gui</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Gui</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gui</em>' attribute list.
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getInteractionTraceExpression_Gui()
   * @model unique="false"
   * @generated
   */
  EList<String> getGui();

  /**
   * Returns the value of the '<em><b>Target L</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target L</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target L</em>' attribute list.
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getInteractionTraceExpression_TargetL()
   * @model unique="false"
   * @generated
   */
  EList<String> getTargetL();

  /**
   * Returns the value of the '<em><b>Target</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' attribute list.
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getInteractionTraceExpression_Target()
   * @model unique="false"
   * @generated
   */
  EList<String> getTarget();

  /**
   * Returns the value of the '<em><b>Minimal L</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Minimal L</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Minimal L</em>' attribute list.
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getInteractionTraceExpression_MinimalL()
   * @model unique="false"
   * @generated
   */
  EList<String> getMinimalL();

  /**
   * Returns the value of the '<em><b>Minimal</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Minimal</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Minimal</em>' attribute list.
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getInteractionTraceExpression_Minimal()
   * @model unique="false"
   * @generated
   */
  EList<String> getMinimal();

  /**
   * Returns the value of the '<em><b>Threshold L</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Threshold L</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Threshold L</em>' attribute list.
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getInteractionTraceExpression_ThresholdL()
   * @model unique="false"
   * @generated
   */
  EList<String> getThresholdL();

  /**
   * Returns the value of the '<em><b>Threshold</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Threshold</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Threshold</em>' attribute list.
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getInteractionTraceExpression_Threshold()
   * @model unique="false"
   * @generated
   */
  EList<String> getThreshold();

  /**
   * Returns the value of the '<em><b>Channels L</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Channels L</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Channels L</em>' attribute list.
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getInteractionTraceExpression_ChannelsL()
   * @model unique="false"
   * @generated
   */
  EList<String> getChannelsL();

  /**
   * Returns the value of the '<em><b>Channels</b></em>' containment reference list.
   * The list contents are of type {@link it.unige.dibris.trace_expression_language.tExp.Channel}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Channels</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Channels</em>' containment reference list.
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getInteractionTraceExpression_Channels()
   * @model containment="true"
   * @generated
   */
  EList<Channel> getChannels();

} // InteractionTraceExpression
