/**
 * generated by Xtext 2.12.0
 */
package it.unige.dibris.trace_expression_language.tExp;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Msg</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.Msg#getAsync_sender <em>Async sender</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.Msg#getReceiver <em>Receiver</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.Msg#getSender <em>Sender</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.Msg#getAsync_receiver <em>Async receiver</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.Msg#getPerformative <em>Performative</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.Msg#getContent <em>Content</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.Msg#getConditions <em>Conditions</em>}</li>
 * </ul>
 *
 * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getMsg()
 * @model
 * @generated
 */
public interface Msg extends EObject
{
  /**
   * Returns the value of the '<em><b>Async sender</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Async sender</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Async sender</em>' reference.
   * @see #setAsync_sender(Role)
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getMsg_Async_sender()
   * @model
   * @generated
   */
  Role getAsync_sender();

  /**
   * Sets the value of the '{@link it.unige.dibris.trace_expression_language.tExp.Msg#getAsync_sender <em>Async sender</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Async sender</em>' reference.
   * @see #getAsync_sender()
   * @generated
   */
  void setAsync_sender(Role value);

  /**
   * Returns the value of the '<em><b>Receiver</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Receiver</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Receiver</em>' reference.
   * @see #setReceiver(Role)
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getMsg_Receiver()
   * @model
   * @generated
   */
  Role getReceiver();

  /**
   * Sets the value of the '{@link it.unige.dibris.trace_expression_language.tExp.Msg#getReceiver <em>Receiver</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Receiver</em>' reference.
   * @see #getReceiver()
   * @generated
   */
  void setReceiver(Role value);

  /**
   * Returns the value of the '<em><b>Sender</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sender</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sender</em>' reference.
   * @see #setSender(Role)
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getMsg_Sender()
   * @model
   * @generated
   */
  Role getSender();

  /**
   * Sets the value of the '{@link it.unige.dibris.trace_expression_language.tExp.Msg#getSender <em>Sender</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sender</em>' reference.
   * @see #getSender()
   * @generated
   */
  void setSender(Role value);

  /**
   * Returns the value of the '<em><b>Async receiver</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Async receiver</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Async receiver</em>' reference.
   * @see #setAsync_receiver(Role)
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getMsg_Async_receiver()
   * @model
   * @generated
   */
  Role getAsync_receiver();

  /**
   * Sets the value of the '{@link it.unige.dibris.trace_expression_language.tExp.Msg#getAsync_receiver <em>Async receiver</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Async receiver</em>' reference.
   * @see #getAsync_receiver()
   * @generated
   */
  void setAsync_receiver(Role value);

  /**
   * Returns the value of the '<em><b>Performative</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Performative</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Performative</em>' attribute.
   * @see #setPerformative(String)
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getMsg_Performative()
   * @model
   * @generated
   */
  String getPerformative();

  /**
   * Sets the value of the '{@link it.unige.dibris.trace_expression_language.tExp.Msg#getPerformative <em>Performative</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Performative</em>' attribute.
   * @see #getPerformative()
   * @generated
   */
  void setPerformative(String value);

  /**
   * Returns the value of the '<em><b>Content</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Content</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content</em>' containment reference.
   * @see #setContent(PrologExpression)
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getMsg_Content()
   * @model containment="true"
   * @generated
   */
  PrologExpression getContent();

  /**
   * Sets the value of the '{@link it.unige.dibris.trace_expression_language.tExp.Msg#getContent <em>Content</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Content</em>' containment reference.
   * @see #getContent()
   * @generated
   */
  void setContent(PrologExpression value);

  /**
   * Returns the value of the '<em><b>Conditions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Conditions</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions</em>' containment reference.
   * @see #setConditions(PrologExpression)
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getMsg_Conditions()
   * @model containment="true"
   * @generated
   */
  PrologExpression getConditions();

  /**
   * Sets the value of the '{@link it.unige.dibris.trace_expression_language.tExp.Msg#getConditions <em>Conditions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conditions</em>' containment reference.
   * @see #getConditions()
   * @generated
   */
  void setConditions(PrologExpression value);

} // Msg
