/**
 * generated by Xtext 2.12.0
 */
package it.unige.dibris.trace_expression_language.tExp;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.VarExpr#getVarExpr <em>Var Expr</em>}</li>
 * </ul>
 *
 * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getVarExpr()
 * @model
 * @generated
 */
public interface VarExpr extends Expression
{
  /**
   * Returns the value of the '<em><b>Var Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Expr</em>' containment reference.
   * @see #setVarExpr(Expression)
   * @see it.unige.dibris.trace_expression_language.tExp.TExpPackage#getVarExpr_VarExpr()
   * @model containment="true"
   * @generated
   */
  Expression getVarExpr();

  /**
   * Sets the value of the '{@link it.unige.dibris.trace_expression_language.tExp.VarExpr#getVarExpr <em>Var Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Expr</em>' containment reference.
   * @see #getVarExpr()
   * @generated
   */
  void setVarExpr(Expression value);

} // VarExpr
