/**
 * generated by Xtext 2.12.0
 */
package it.unige.dibris.trace_expression_language.tExp.impl;

import it.unige.dibris.trace_expression_language.tExp.Constraint;
import it.unige.dibris.trace_expression_language.tExp.Role;
import it.unige.dibris.trace_expression_language.tExp.TExpPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Constraint</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.impl.ConstraintImpl#getLeft <em>Left</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.impl.ConstraintImpl#getTogether <em>Together</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.impl.ConstraintImpl#getRight <em>Right</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.impl.ConstraintImpl#getSplit <em>Split</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.impl.ConstraintImpl#getParMin <em>Par Min</em>}</li>
 *   <li>{@link it.unige.dibris.trace_expression_language.tExp.impl.ConstraintImpl#getParMax <em>Par Max</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ConstraintImpl extends MinimalEObjectImpl.Container implements Constraint
{
  /**
   * The cached value of the '{@link #getLeft() <em>Left</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLeft()
   * @generated
   * @ordered
   */
  protected EList<Role> left;

  /**
   * The default value of the '{@link #getTogether() <em>Together</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTogether()
   * @generated
   * @ordered
   */
  protected static final String TOGETHER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTogether() <em>Together</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTogether()
   * @generated
   * @ordered
   */
  protected String together = TOGETHER_EDEFAULT;

  /**
   * The cached value of the '{@link #getRight() <em>Right</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRight()
   * @generated
   * @ordered
   */
  protected EList<Role> right;

  /**
   * The default value of the '{@link #getSplit() <em>Split</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSplit()
   * @generated
   * @ordered
   */
  protected static final String SPLIT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSplit() <em>Split</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSplit()
   * @generated
   * @ordered
   */
  protected String split = SPLIT_EDEFAULT;

  /**
   * The default value of the '{@link #getParMin() <em>Par Min</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParMin()
   * @generated
   * @ordered
   */
  protected static final String PAR_MIN_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getParMin() <em>Par Min</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParMin()
   * @generated
   * @ordered
   */
  protected String parMin = PAR_MIN_EDEFAULT;

  /**
   * The default value of the '{@link #getParMax() <em>Par Max</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParMax()
   * @generated
   * @ordered
   */
  protected static final String PAR_MAX_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getParMax() <em>Par Max</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParMax()
   * @generated
   * @ordered
   */
  protected String parMax = PAR_MAX_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConstraintImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TExpPackage.Literals.CONSTRAINT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Role> getLeft()
  {
    if (left == null)
    {
      left = new EObjectResolvingEList<Role>(Role.class, this, TExpPackage.CONSTRAINT__LEFT);
    }
    return left;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getTogether()
  {
    return together;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTogether(String newTogether)
  {
    String oldTogether = together;
    together = newTogether;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TExpPackage.CONSTRAINT__TOGETHER, oldTogether, together));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Role> getRight()
  {
    if (right == null)
    {
      right = new EObjectResolvingEList<Role>(Role.class, this, TExpPackage.CONSTRAINT__RIGHT);
    }
    return right;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getSplit()
  {
    return split;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSplit(String newSplit)
  {
    String oldSplit = split;
    split = newSplit;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TExpPackage.CONSTRAINT__SPLIT, oldSplit, split));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getParMin()
  {
    return parMin;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setParMin(String newParMin)
  {
    String oldParMin = parMin;
    parMin = newParMin;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TExpPackage.CONSTRAINT__PAR_MIN, oldParMin, parMin));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getParMax()
  {
    return parMax;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setParMax(String newParMax)
  {
    String oldParMax = parMax;
    parMax = newParMax;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TExpPackage.CONSTRAINT__PAR_MAX, oldParMax, parMax));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TExpPackage.CONSTRAINT__LEFT:
        return getLeft();
      case TExpPackage.CONSTRAINT__TOGETHER:
        return getTogether();
      case TExpPackage.CONSTRAINT__RIGHT:
        return getRight();
      case TExpPackage.CONSTRAINT__SPLIT:
        return getSplit();
      case TExpPackage.CONSTRAINT__PAR_MIN:
        return getParMin();
      case TExpPackage.CONSTRAINT__PAR_MAX:
        return getParMax();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TExpPackage.CONSTRAINT__LEFT:
        getLeft().clear();
        getLeft().addAll((Collection<? extends Role>)newValue);
        return;
      case TExpPackage.CONSTRAINT__TOGETHER:
        setTogether((String)newValue);
        return;
      case TExpPackage.CONSTRAINT__RIGHT:
        getRight().clear();
        getRight().addAll((Collection<? extends Role>)newValue);
        return;
      case TExpPackage.CONSTRAINT__SPLIT:
        setSplit((String)newValue);
        return;
      case TExpPackage.CONSTRAINT__PAR_MIN:
        setParMin((String)newValue);
        return;
      case TExpPackage.CONSTRAINT__PAR_MAX:
        setParMax((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TExpPackage.CONSTRAINT__LEFT:
        getLeft().clear();
        return;
      case TExpPackage.CONSTRAINT__TOGETHER:
        setTogether(TOGETHER_EDEFAULT);
        return;
      case TExpPackage.CONSTRAINT__RIGHT:
        getRight().clear();
        return;
      case TExpPackage.CONSTRAINT__SPLIT:
        setSplit(SPLIT_EDEFAULT);
        return;
      case TExpPackage.CONSTRAINT__PAR_MIN:
        setParMin(PAR_MIN_EDEFAULT);
        return;
      case TExpPackage.CONSTRAINT__PAR_MAX:
        setParMax(PAR_MAX_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TExpPackage.CONSTRAINT__LEFT:
        return left != null && !left.isEmpty();
      case TExpPackage.CONSTRAINT__TOGETHER:
        return TOGETHER_EDEFAULT == null ? together != null : !TOGETHER_EDEFAULT.equals(together);
      case TExpPackage.CONSTRAINT__RIGHT:
        return right != null && !right.isEmpty();
      case TExpPackage.CONSTRAINT__SPLIT:
        return SPLIT_EDEFAULT == null ? split != null : !SPLIT_EDEFAULT.equals(split);
      case TExpPackage.CONSTRAINT__PAR_MIN:
        return PAR_MIN_EDEFAULT == null ? parMin != null : !PAR_MIN_EDEFAULT.equals(parMin);
      case TExpPackage.CONSTRAINT__PAR_MAX:
        return PAR_MAX_EDEFAULT == null ? parMax != null : !PAR_MAX_EDEFAULT.equals(parMax);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (together: ");
    result.append(together);
    result.append(", split: ");
    result.append(split);
    result.append(", parMin: ");
    result.append(parMin);
    result.append(", parMax: ");
    result.append(parMax);
    result.append(')');
    return result.toString();
  }

} //ConstraintImpl
