/**
 * generated by Xtext 2.12.0
 */
package it.unige.dibris.trace_expression_language.ui;

import it.unige.dibris.trace_expression_language.ui.AbstractTExpUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TExpUiModule extends AbstractTExpUiModule {
  public TExpUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
