/*
 * generated by Xtext 2.12.0
 */
package it.unige.dibris.trace_expression_language


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TExpRuntimeModule extends AbstractTExpRuntimeModule {
}
