/**
 * generated by Xtext 2.12.0
 */
package it.unige.dibris.trace_expression_language.ide;

import it.unige.dibris.trace_expression_language.ide.AbstractTExpIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TExpIdeModule extends AbstractTExpIdeModule {
}
